POST http://localhost:3001/api/products
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYWI2OTJlMDFjZGFkMzM2ODZhZjU5MiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY3MjE3ODA1NCwiZXhwIjoxNjcyNDM3MjU0fQ.-hJXfsHKpREuWcDByTCTBWmJzhynA6oVSTqWXT2DBQE

{
    "title":"Producto 9",
    "desc":"2213",
    "category": "men",
    "img":[
        "/dsadsadasdsa",
        "/dhsajdghasjd",
        "/dsadsadasdsad",
        "/ddsadsahdsjkah"
    ],
    "size":[
        "40",
        "41",
        "42",
        "43",
        "44",
        "45",
        "46"
    ],
    "color":[
        "white",
        "black",
        "red",
        "green"
    ],
    "price":18,
    "inStock":false
}