DELETE http://localhost:3001/api/carts/63a4b266855fc0727366dbf5
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTNhNDllMDFjNmRjMmYxNDFjNDQ4NiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzE3NDQ1MjEsImV4cCI6MTY3MjAwMzcyMX0.G0Xmt8q-kkO25D6SYEMny0CSom81SZGzkPBajNSqtS4