GET http://localhost:3001/api/carts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTNhMThhNjIyMDJmM2QxMTQ4YjQ2ZiIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzE2Njg3MjYsImV4cCI6MTY3MTkyNzkyNn0.xY67l0gN4wCqa4rKVJqzZbQza5io_IXX1hKjJPqgDpc