POST http://localhost:3001/api/carts
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTM2OTAyOThlM2JjNjc2NTBhNTE1NSIsImlzQWRtaW4iOmZhbHNlLCJpYXQiOjE2NzE2NTM2NDUsImV4cCI6MTY3MTkxMjg0NX0.OHXb3K_AJv8mHms0LmaYj8M-cpSCNOS94e5oiiETRuw

{
    "title":"Producto 10",
    "productId":"123456",
    "quantity": 2,
    "color":"red",
    "img":"/dsadsadsa"
}