DELETE http://localhost:3001/api/orders/637edb5c85f606b53d34ce17
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzN2U4Mjg3ODE3YTA0OTI4MGNlNzc0MCIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY2OTIzNTQ2MywiZXhwIjoxNjY5NDk0NjYzfQ.jqDu747c6IqSjmCls-tcrVnccd3L0c9sE-U8VyyA_CM