GET http://localhost:3001/api/users/63a3516d2069c874f392e76b
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzYTM1MTZkMjA2OWM4NzRmMzkyZTc2YiIsImlzQWRtaW4iOnRydWUsImlhdCI6MTY3MTY0OTE0MiwiZXhwIjoxNjcxOTA4MzQyfQ.EYsdnhCB_cQ3Y-Iks8WsSxDGeQ-M2zbFsTrk0c0XO_E